# Generated by Django 6.0.3 on 2026-03-21 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grimoire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('fundador', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='casa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros', to='grimoire.casa'),
        ),
    ]
